
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.HBox hbox2;

	private global::Gtk.VBox vbox3;

	private global::Gtk.Label label2;

	private global::Gtk.Label label3;

	private global::Gtk.VBox vbox4;

	private global::Gtk.Entry txtPlano;

	private global::Gtk.Entry txtDesplazamiento;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Alignment alignment1;

	private global::Gtk.Button btnCifrar;

	private global::Gtk.HBox hbox4;

	private global::Gtk.VBox vbox5;

	private global::Gtk.Label label4;

	private global::Gtk.Label label5;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView txtCifradoCesar;

	private global::Gtk.VBox vbox6;

	private global::Gtk.Label label6;

	private global::Gtk.Label label7;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView txtCifradoInverso;

	private global::Gtk.VBox vbox7;

	private global::Gtk.Label label8;

	private global::Gtk.Label label9;

	private global::Gtk.ScrolledWindow GtkScrolledWindow2;

	private global::Gtk.TextView txtCifradoInversoGrupal;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Texto Plano");
		this.vbox3.Add(this.label2);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label2]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Desplazamiento:");
		this.vbox3.Add(this.label3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label3]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.hbox2.Add(this.vbox3);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox3]));
		w3.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.txtPlano = new global::Gtk.Entry();
		this.txtPlano.CanFocus = true;
		this.txtPlano.Name = "txtPlano";
		this.txtPlano.IsEditable = true;
		this.txtPlano.InvisibleChar = '●';
		this.vbox4.Add(this.txtPlano);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.txtPlano]));
		w4.Position = 0;
		w4.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.txtDesplazamiento = new global::Gtk.Entry();
		this.txtDesplazamiento.CanFocus = true;
		this.txtDesplazamiento.Name = "txtDesplazamiento";
		this.txtDesplazamiento.IsEditable = true;
		this.txtDesplazamiento.InvisibleChar = '●';
		this.vbox4.Add(this.txtDesplazamiento);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.txtDesplazamiento]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		this.hbox3.Add(this.alignment1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.alignment1]));
		w6.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btnCifrar = new global::Gtk.Button();
		this.btnCifrar.CanFocus = true;
		this.btnCifrar.Name = "btnCifrar";
		this.btnCifrar.UseUnderline = true;
		this.btnCifrar.Label = global::Mono.Unix.Catalog.GetString("Cifrar");
		this.hbox3.Add(this.btnCifrar);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btnCifrar]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox4.Add(this.hbox3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox3]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		this.hbox2.Add(this.vbox4);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox4]));
		w9.Position = 1;
		this.hbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox2]));
		w10.Position = 0;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("CESAR");
		this.vbox5.Add(this.label4);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label4]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Texto cifrado:");
		this.vbox5.Add(this.label5);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label5]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.txtCifradoCesar = new global::Gtk.TextView();
		this.txtCifradoCesar.CanFocus = true;
		this.txtCifradoCesar.Name = "txtCifradoCesar";
		this.GtkScrolledWindow.Add(this.txtCifradoCesar);
		this.vbox5.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.GtkScrolledWindow]));
		w15.Position = 2;
		this.hbox4.Add(this.vbox5);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox5]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("INVERSO");
		this.vbox6.Add(this.label6);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label6]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Texto Cifrado:");
		this.vbox6.Add(this.label7);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label7]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.txtCifradoInverso = new global::Gtk.TextView();
		this.txtCifradoInverso.CanFocus = true;
		this.txtCifradoInverso.Name = "txtCifradoInverso";
		this.GtkScrolledWindow1.Add(this.txtCifradoInverso);
		this.vbox6.Add(this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.GtkScrolledWindow1]));
		w20.Position = 2;
		this.hbox4.Add(this.vbox6);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox6]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("INVERSO GRUPAL");
		this.vbox7.Add(this.label8);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label8]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Texto Cifrado:");
		this.vbox7.Add(this.label9);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label9]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.txtCifradoInversoGrupal = new global::Gtk.TextView();
		this.txtCifradoInversoGrupal.CanFocus = true;
		this.txtCifradoInversoGrupal.Name = "txtCifradoInversoGrupal";
		this.GtkScrolledWindow2.Add(this.txtCifradoInversoGrupal);
		this.vbox7.Add(this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.GtkScrolledWindow2]));
		w25.Position = 2;
		this.hbox4.Add(this.vbox7);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox7]));
		w26.Position = 2;
		w26.Expand = false;
		w26.Fill = false;
		this.vbox1.Add(this.hbox4);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
		w27.Position = 1;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 853;
		this.DefaultHeight = 442;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnCifrar.Clicked += new global::System.EventHandler(this.OnBtnCifrarClicked);
	}
}
