//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cifrado {
    
    
    public partial class Default {
        
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        
        protected System.Web.UI.WebControls.TextBox textoPlano;
        
        protected System.Web.UI.WebControls.TextBox txtDesplazamiento;
        
        protected System.Web.UI.WebControls.Button btnConvertir;
        
        protected System.Web.UI.HtmlControls.HtmlGenericControl txtCifradoCesar;
        
        protected System.Web.UI.HtmlControls.HtmlGenericControl txtCifradoInverso;
        
        protected System.Web.UI.HtmlControls.HtmlGenericControl txtCifradoInversoGrupal;
    }
}
